apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy49
  labels:
    app: autodeploy49
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717447356106
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy49
  template:
    metadata:
      labels:
        app: autodeploy49
    spec:
      containers:
        - name: autodeploy49
          image: acrworkflow1717447356106.azurecr.io/image-workflow-1717447356106:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
