apiVersion: v1
kind: Service
metadata:
  name: autodeploy49
  namespace: namespace-workflow-1717447356106
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy49
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000